### ISSUE TITLE
Models missing

### ISSUE THREAD

**Issue by vergissberlin** [Poseyy/StreamlitDemos#2]
Hi @Poseyy,

please check in the models too and a small introduction in the readme.

```
OSError: Unable to open file (unable to open file: name = './models/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

Thank you!
André

**Comment by Poseyy** [comment]
Hi @vergissberlin this is not possible as the file size for the model is too large. You can generate your own model by running the application using streamlit run demo.py and clicking the train button or alternatively you can use training.py to train your own model from the command line. 

I've added a readme that should help; there are some steps you need to follow to get things setup. Let me know if you have any additional questions!

**Comment by vergissberlin** [comment]
Hi @Poseyy !

I've tried it with the current version with the same result:
![image](https://user-images.githubusercontent.com/179964/67672279-e6326e80-f977-11e9-9bb0-3913a39e9c3f.png)

Then, I've created empty files, because you mean these files will be generated. But then I got the error
![image](https://user-images.githubusercontent.com/179964/67673264-f77c7a80-f979-11e9-8c22-b121e0e09ed4.png)

Sorry, I am not very familiar with python ... What else I have to do?

best wishes,
André

**Comment by Poseyy** [comment]
@vergissberlin Take a shot at following the readme. There are a handful of steps you need to take. You need to train your own models to get this up and running.
